### ISSUE TITLE
Arrays in custom.json are not displayed

### ISSUE THREAD

**Issue by evgfilim1** [ark0f/tg-bot-api#1]
## Description
In `custom.json` arrays are not displayed, they are just `reference`s to inner object. But in `openapi.*` they are displayed correctly.
For example, [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) method accepts array of `InputMedia*` and returns array of `Message`s.

## Expected behaviour
Something like this:
```json
{
  "return_type": {
    "type": "array",
    "array_of": "reference",
    "reference": "Message"
  }
}
```

## Actual behaviour
![image](https://user-images.githubusercontent.com/17182159/99765617-4109ab80-2b21-11eb-8578-dceb391eb7ed.png)

![image](https://user-images.githubusercontent.com/17182159/99765732-84641a00-2b21-11eb-8641-6f6519cfe16a.png)

**Comment by ark0f** [comment]
Fixed and deployed
