### ISSUE TITLE
Instructions on how to manually compile and run?

### ISSUE THREAD

**Issue by nitreojs** [ark0f/tg-bot-api#10]
I'm not writing on Rust and not even understanding it's basic syntax, but in case if this repository won't update in time when new Bot API update releases I want to generate schemas manually. But since I'm not a fan of Rust, I actually don't know how to compile and run that code. Could you make a documentation page or something that will be describing steps on how to generate schemas manually?

Just basic stuff like _"before compiling make sure that you have at least X.X version of Rust installed, ..."_ and steps on how to compile the code and run it

**Comment by ark0f** [comment]
> if this repository won't update in time when new Bot API update releases

Repository automatically updates every day, so it's always up to date

But if you insist, I will write steps
