### ISSUE TITLE
Return Type Description

### ISSUE THREAD

**Issue by jonasgeiler** [ark0f/tg-bot-api#12]
Would it be possible to parse the return type description?

For example, instead of:
```json
"return_type": {
  "type": "bool",
  "default": true
}
```
it generates this:
```json
"return_type": {
  "description": "Returns *True* on success.", 
  "type": "bool",
  "default": true
}
```

I'm not sure how your Parser works, but if it's based on Regular Expressions, you could just use the full match.

**Comment by ark0f** [comment]
I don't understand what this description for.

There are few patterns:
* `Returns *SOMETING* on success.`
* `An *SOMETHING is returned`
* `On success *SOMETHING* is returned`

They are so generic and useless for reader, so I don't see their usage

**Comment by jonasgeiler** [comment]
True, I guess.
There are some more complicated ones like:
- `On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.`
- `On success, returns an Array of ChatMember objects that contains information about all chat administrators except other bots.`

But for them you could just read the method description...
Well, if you're not adding this then you can close this issue.

**Comment by ark0f** [comment]
Also these sentences are about _method_, so you can misunderstood description
