### ISSUE TITLE
Don't use default property for "must be"-types

### ISSUE THREAD

**Issue by jonasgeiler** [ark0f/tg-bot-api#13]
Currently the `type` property of `InputMediaPhoto` looks like this:
```json
{
  "name": "type",
  "description": "Type of the result, must be *photo*",
  "required": true,
  "type": "string",
  "default": "photo"
},
```
The description says the value **must be** `"photo"`, but this is specified as a "default" value.
I think it would be much clearer to use another property name, like `mustBe`, or use the existing `enumeration` with only one option.
Like this:
```json
{
  "name": "type",
  "description": "Type of the result, must be *photo*",
  "required": true,
  "type": "string",
  "enumeration": [ "photo" ]
},
```

Let me know what you think!
Thanks in advance!

**Comment by ark0f** [comment]
> it would be much clearer

You are right


> another property name

It's not possible right now because I have to save backward compatibility


> use the existing enumeration with only one option

It might be a good solution, but this string is not an actual enumeration and may affect existing user generators


I'd preffer to add field like `is_only_value` (so we can save compatibility) but I'm not sure field like this will be helpful when working with the schema

**Comment by jonasgeiler** [comment]
I think the enumeration might be the best solution because OpenAPI only supports using enumeration, and you'd have to use an enumeration with a single item in `openapi.json` anyways.
The same property in `openapi.json` currently looks like this:
```json
"type": {
  "description": "Type of the result, must be *photo*",
  "default": "photo",
  "type": "string"
}
```
... which is also a bit misleading.
And there isn't really any way to do this other than using `enum`.

But if you're really not into using an enumeration, JSON Schema uses `"const": "some value"` to achieve this. Maybe you could use `"const"` aswell for a bit of clarity.

P.S.: In `custom.schema.json` you actually use `enum` with a single value for the `type` properties.

**Comment by ark0f** [comment]
About JSON Schema "const"; according to draft #<span>7:
> It should be noted that const is merely syntactic sugar for an enum with a single element, therefore the following are equivalent:
```json
{ "const": "United States of America" }

{ "enum": [ "United States of America" ] }
```

I agree with your suggestions, but I'm still afraid of breaking backward compatibility.

> you actually use enum with a single value

I actually don't, JSON Schema generator does

**Comment by ark0f** [comment]
I am preparing custom schema v2 now and faced this argument from `sendPoll` method:
```json
{
    "name": "type",
    "description": "Poll type, “quiz” or “regular”, defaults to “regular”",
    "required": false,
    "type": "string",
    "default": "regular",
    "enumeration": [
        "quiz",
        "regular"
    ]
},
```
So I don't think it is possible to apply your suggestion
