### ISSUE TITLE
Emojis are left as `<img />` tags

### ISSUE THREAD

**Issue by evgfilim1** [ark0f/tg-bot-api#7]
# Description
Emojis in the description of [`sendDice`](https://core.telegram.org/bots/api/#senddice) are returned as plain HTML like this:
`<img alt="🎲" src="//telegram.org/img/emoji/40/F09F8EB2.png" height="20" width="20" />`. This applies to both [`custom.json`](https://ark0f.github.io/tg-bot-api/custom.json) and [`openapi.json`](https://ark0f.github.io/tg-bot-api/openapi.json).

# Expected behavior
```json
{
  "name": "emoji",
  "description": "Emoji on which the dice throw animation is based. Currently, must be one of “🎲”, “🎯”, “🏀”, “⚽”, “🎳”, or “🎰”. Dice can have values 1-6 for “🎲”, “🎯” and “🎳”, values 1-5 for “🏀” and “⚽”, and values 1-64 for “🎰”. Defaults to “🎲”",
  "required": false,
  "type": "string",
  "default": "🎲",
  "enumeration": [
    "🎲",
    "🎯",
    "🏀",
    "⚽",
    "🎳",
    "🎰"
  ]
},
```

# Actual behavior
![custom.json](https://user-images.githubusercontent.com/17182159/117442085-bcd0a680-af4f-11eb-99d6-6d2fdac4ca0b.png)

**Comment by ark0f** [comment]
Descriptions are in markdown format, which implies that `<img>` tags are valid. I left them because emojis can look differently on platforms, can be not supported to display, etc. Of course I can get rid of these tags, but I'm not sure this is needed

**Comment by evgfilim1** [comment]
IMHO it's user's responsibility to make these descriptions readable/viewable, like installing or embedding fonts that support emoji.

---

### Pros of leaving tags:
+ They look the same everywhere when rendered

### Cons:
- These tags look weird in code:
![image](https://user-images.githubusercontent.com/17182159/117449171-18536200-af59-11eb-9816-ae26d641e360.png)
- They're not rendered in IntelliJ-based IDEs:
![image](https://user-images.githubusercontent.com/17182159/117449266-3620c700-af59-11eb-9e77-9a0c33a218f8.png)
![image](https://user-images.githubusercontent.com/17182159/117449877-ebec1580-af59-11eb-887e-61b9836cb2de.png)
- And they look weird in Dokka-rendered HTML docs by default:
![image](https://user-images.githubusercontent.com/17182159/117449354-5486c280-af59-11eb-922b-2aefa6690f20.png)

---

Yeah I know I can change stylesheet to show them inlined, but two other cons still exist.
Of course I can modify the description after I get it from json to suit my needs and wishes, but I'd like those tags to be already transformed to emoji.

So, that's my opinion and expectations. If you think it's better to leave them as-is, no problem.
