### ISSUE TITLE
Duplicated link tag in argument description

### ISSUE THREAD

**Issue by evgfilim1** [ark0f/tg-bot-api#8]
When no link text is specified [1], the link tag is duplicated like this [2]:
`[](https://core.telegram.org/animated_stickers#technical-requirements)[https://core.telegram.org/animated\\_stickers#technical-requirements](https://core.telegram.org/animated_stickers#technical-requirements)`

After some investigation, I've noticed that it's upstream bug:
![html-src](https://user-images.githubusercontent.com/17182159/117552339-2641d980-b064-11eb-838d-77df2813589a.png)

Maybe we should workaround this?

---

1. ![docs](https://user-images.githubusercontent.com/17182159/117552085-df071900-b062-11eb-9ca4-bfb517fc460e.png)
2. ![json](https://user-images.githubusercontent.com/17182159/117552460-e2030900-b064-11eb-90e2-7cb9f8026f91.png)

**Comment by ark0f** [comment]
I hope this and #7 issues are now fixed. If not, reopen them
