### ISSUE TITLE
"must be" unions for interface fields?

### ISSUE THREAD

**Issue by nitreojs** [ark0f/tg-bot-api#9]
this may be the `{ ... type: "string", default: "reverse_side" }` or something like that:

<img width="624" alt="must be" src="https://user-images.githubusercontent.com/40319427/118407351-1b50ff80-b689-11eb-875e-bedf6ee7d639.png">

**Comment by nitreojs** [comment]
didn't see about the second one, it's already implemented via `{ enumeration: ['driver_license', 'identity_card'] }`, but the first one does not have any enumeration or default value

**Comment by ark0f** [comment]
Will be fixed soon

**Comment by ark0f** [comment]
This issue must be fixed now.
Please, verify fix using dev link:
https://ark0f.github.io/tg-bot-api/dev/custom.json

**Comment by nitreojs** [comment]
yes, everything works so far now!

what do I need to do now? seems like this change is only in /dev/

**Comment by nitreojs** [comment]
oh wait, something is wrong for sure: parameter `type` for method `sendPoll` has got `default: 'regular'`, even tho it's `description` has `“quiz” or “regular”` in it; seems like the script only checks either for `defaults to` or `One of` etc. areas

<details>
  <summary> <code>sendPoll</code> and it's parameter <code>type</code> </summary>

  <img width="564" alt="image" src="https://user-images.githubusercontent.com/40319427/119353984-308ee500-bcac-11eb-8cc8-759f8cfec59b.png">
</details>

... and also, `Poll` object and it's parameter `type` has `can be “regular” or “quiz”` in `description`, but does not have `enumeration` field

<details>
  <summary> <code>Poll</code> and it's <code>type</code> and <code>description</code> </summary>

  <img width="550" alt="image" src="https://user-images.githubusercontent.com/40319427/119353072-1d2f4a00-bcab-11eb-89fd-e7e39ad03945.png">
</details>

**Comment by ark0f** [comment]
> what do I need to do now? seems like this change is only in /dev/

Wait until I merge `dev` branch into `master`, then fixed files will be automatically deployed

> sendPoll and it's parameter type

> Poll and it's type and description

That's another issue I have to fix...

**Comment by nitreojs** [comment]
alright, so I will let this issue be opened so you can refer to it in commits or just close it / write here when it's test time or when it's fixed

**Comment by ark0f** [comment]
Ok. I fixed these two issues. Check again, please

**Comment by nitreojs** [comment]
seems like everything's ok now! 😎
